// リロードごとにランダムなGoogle無料フォントを1つだけ読み込む（日英で出し分け）。
// 1回の表示で読むのは1フォントだけなので、候補が多くても速度に影響しない。
(function () {
  var ja = [
    { css: '"Noto Sans JP",sans-serif', g: 'Noto+Sans+JP:wght@400;700;900' },
    { css: '"Noto Serif JP",serif', g: 'Noto+Serif+JP:wght@400;700;900' },
    { css: '"Zen Kaku Gothic New",sans-serif', g: 'Zen+Kaku+Gothic+New:wght@400;700;900' },
    { css: '"Zen Kaku Gothic Antique",sans-serif', g: 'Zen+Kaku+Gothic+Antique:wght@400;700;900' },
    { css: '"Zen Maru Gothic",sans-serif', g: 'Zen+Maru+Gothic:wght@400;700;900' },
    { css: '"Zen Old Mincho",serif', g: 'Zen+Old+Mincho:wght@400;700;900' },
    { css: '"Zen Antique",serif', g: 'Zen+Antique' },
    { css: '"Zen Antique Soft",serif', g: 'Zen+Antique+Soft' },
    { css: '"Zen Kurenaido",sans-serif', g: 'Zen+Kurenaido' },
    { css: '"M PLUS 1",sans-serif', g: 'M+PLUS+1:wght@400;700;800' },
    { css: '"M PLUS 2",sans-serif', g: 'M+PLUS+2:wght@400;700;800' },
    { css: '"M PLUS 1p",sans-serif', g: 'M+PLUS+1p:wght@400;700;800' },
    { css: '"M PLUS Rounded 1c",sans-serif', g: 'M+PLUS+Rounded+1c:wght@400;700;800' },
    { css: '"Kosugi",sans-serif', g: 'Kosugi' },
    { css: '"Kosugi Maru",sans-serif', g: 'Kosugi+Maru' },
    { css: '"Sawarabi Gothic",sans-serif', g: 'Sawarabi+Gothic' },
    { css: '"Sawarabi Mincho",serif', g: 'Sawarabi+Mincho' },
    { css: '"BIZ UDGothic",sans-serif', g: 'BIZ+UDGothic:wght@400;700' },
    { css: '"BIZ UDPGothic",sans-serif', g: 'BIZ+UDPGothic:wght@400;700' },
    { css: '"BIZ UDMincho",serif', g: 'BIZ+UDMincho:wght@400;700' },
    { css: '"BIZ UDPMincho",serif', g: 'BIZ+UDPMincho' },
    { css: '"Shippori Mincho",serif', g: 'Shippori+Mincho:wght@400;700;800' },
    { css: '"Shippori Mincho B1",serif', g: 'Shippori+Mincho+B1:wght@400;700;800' },
    { css: '"Shippori Antique",sans-serif', g: 'Shippori+Antique' },
    { css: '"Shippori Antique B1",sans-serif', g: 'Shippori+Antique+B1' },
    { css: '"Kaisei Decol",serif', g: 'Kaisei+Decol:wght@400;700' },
    { css: '"Kaisei Opti",serif', g: 'Kaisei+Opti:wght@400;700' },
    { css: '"Kaisei Tokumin",serif', g: 'Kaisei+Tokumin:wght@400;700;800' },
    { css: '"Kaisei HarunoUmi",serif', g: 'Kaisei+HarunoUmi:wght@400;700' },
    { css: '"Klee One",cursive', g: 'Klee+One:wght@400;600' },
    { css: '"Yomogi",cursive', g: 'Yomogi' },
    { css: '"Hina Mincho",serif', g: 'Hina+Mincho' },
    { css: '"New Tegomin",serif', g: 'New+Tegomin' },
    { css: '"Yuji Syuku",serif', g: 'Yuji+Syuku' },
    { css: '"Yuji Boku",serif', g: 'Yuji+Boku' },
    { css: '"Yuji Mai",serif', g: 'Yuji+Mai' },
    { css: '"Kiwi Maru",serif', g: 'Kiwi+Maru:wght@400;500' },
    { css: '"Murecho",sans-serif', g: 'Murecho:wght@400;700;800' },
    { css: '"IBM Plex Sans JP",sans-serif', g: 'IBM+Plex+Sans+JP:wght@400;700' },
    { css: '"Dela Gothic One",sans-serif', g: 'Dela+Gothic+One' },
    { css: '"Reggae One",sans-serif', g: 'Reggae+One' },
    { css: '"RocknRoll One",sans-serif', g: 'RocknRoll+One' },
    { css: '"Train One",sans-serif', g: 'Train+One' },
    { css: '"DotGothic16",sans-serif', g: 'DotGothic16' },
    { css: '"Hachi Maru Pop",cursive', g: 'Hachi+Maru+Pop' },
    { css: '"Potta One",cursive', g: 'Potta+One' },
    { css: '"Rampart One",sans-serif', g: 'Rampart+One' },
    { css: '"Stick",sans-serif', g: 'Stick' },
    { css: '"Yusei Magic",sans-serif', g: 'Yusei+Magic' },
    { css: '"Cherry Bomb One",cursive', g: 'Cherry+Bomb+One' },
    { css: '"Slackside One",cursive', g: 'Slackside+One' },
    { css: '"Mochiy Pop One",sans-serif', g: 'Mochiy+Pop+One' },
    { css: '"Mochiy Pop P One",sans-serif', g: 'Mochiy+Pop+P+One' },
    { css: '"Chokokutai",cursive', g: 'Chokokutai' },
    { css: '"Palette Mosaic",sans-serif', g: 'Palette+Mosaic' },
    { css: '"Shizuru",cursive', g: 'Shizuru' }
  ];

  var en = [
    { css: '"Caveat",cursive', g: 'Caveat:wght@400;700' },
    { css: '"Caveat Brush",cursive', g: 'Caveat+Brush' },
    { css: '"Architects Daughter",cursive', g: 'Architects+Daughter' },
    { css: '"Patrick Hand",cursive', g: 'Patrick+Hand' },
    { css: '"Patrick Hand SC",cursive', g: 'Patrick+Hand+SC' },
    { css: '"Shadows Into Light",cursive', g: 'Shadows+Into+Light' },
    { css: '"Shadows Into Light Two",cursive', g: 'Shadows+Into+Light+Two' },
    { css: '"Kalam",cursive', g: 'Kalam:wght@300;400;700' },
    { css: '"Gloria Hallelujah",cursive', g: 'Gloria+Hallelujah' },
    { css: '"Indie Flower",cursive', g: 'Indie+Flower' },
    { css: '"Gochi Hand",cursive', g: 'Gochi+Hand' },
    { css: '"Reenie Beanie",cursive', g: 'Reenie+Beanie' },
    { css: '"Nanum Pen Script",cursive', g: 'Nanum+Pen+Script' },
    { css: '"Nanum Brush Script",cursive', g: 'Nanum+Brush+Script' },
    { css: '"Permanent Marker",cursive', g: 'Permanent+Marker' },
    { css: '"Rock Salt",cursive', g: 'Rock+Salt' },
    { css: '"Sriracha",cursive', g: 'Sriracha' },
    { css: '"Handlee",cursive', g: 'Handlee' },
    { css: '"Coming Soon",cursive', g: 'Coming+Soon' },
    { css: '"Just Another Hand",cursive', g: 'Just+Another+Hand' },
    { css: '"Dancing Script",cursive', g: 'Dancing+Script:wght@400;700' },
    { css: '"Pacifico",cursive', g: 'Pacifico' },
    { css: '"Satisfy",cursive', g: 'Satisfy' },
    { css: '"Kaushan Script",cursive', g: 'Kaushan+Script' },
    { css: '"Gaegu",cursive', g: 'Gaegu:wght@300;400;700' },
    { css: '"Neucha",cursive', g: 'Neucha' },
    { css: '"Schoolbell",cursive', g: 'Schoolbell' },
    { css: '"Walter Turncoat",cursive', g: 'Walter+Turncoat' },
    { css: '"Short Stack",cursive', g: 'Short+Stack' },
    { css: '"Sue Ellen Francisco",cursive', g: 'Sue+Ellen+Francisco' },
    { css: '"Cookie",cursive', g: 'Cookie' },
    { css: '"Marck Script",cursive', g: 'Marck+Script' },
    { css: '"Homemade Apple",cursive', g: 'Homemade+Apple' },
    { css: '"La Belle Aurore",cursive', g: 'La+Belle+Aurore' },
    { css: '"Mansalva",cursive', g: 'Mansalva' },
    { css: '"Delius",cursive', g: 'Delius' },
    { css: '"Delius Swash Caps",cursive', g: 'Delius+Swash+Caps' },
    { css: '"Delius Unicase",cursive', g: 'Delius+Unicase' },
    { css: '"Itim",cursive', g: 'Itim' },
    { css: '"Comforter",cursive', g: 'Comforter' },
    { css: '"Comforter Brush",cursive', g: 'Comforter+Brush' },
    { css: '"Bad Script",cursive', g: 'Bad+Script' },
    { css: '"Amatic SC",cursive', g: 'Amatic+SC:wght@400;700' },
    { css: '"Annie Use Your Telescope",cursive', g: 'Annie+Use+Your+Telescope' },
    { css: '"Beth Ellen",cursive', g: 'Beth+Ellen' },
    { css: '"Cedarville Cursive",cursive', g: 'Cedarville+Cursive' },
    { css: '"Covered By Your Grace",cursive', g: 'Covered+By+Your+Grace' },
    { css: '"Dawning of a New Day",cursive', g: 'Dawning+of+a+New+Day' },
    { css: '"Felipa",cursive', g: 'Felipa' },
    { css: '"Fondamento",cursive', g: 'Fondamento' },
    { css: '"Give You Glory",cursive', g: 'Give+You+Glory' },
    { css: '"Great Vibes",cursive', g: 'Great+Vibes' },
    { css: '"Herr Von Muellerhoff",cursive', g: 'Herr+Von+Muellerhoff' },
    { css: '"Kristi",cursive', g: 'Kristi' },
    { css: '"Leckerli One",cursive', g: 'Leckerli+One' },
    { css: '"Loved by the King",cursive', g: 'Loved+by+the+King' },
    { css: '"Meddon",cursive', g: 'Meddon' },
    { css: '"Merienda",cursive', g: 'Merienda:wght@400;700' },
    { css: '"Montez",cursive', g: 'Montez' },
    { css: '"Mr Dafoe",cursive', g: 'Mr+Dafoe' },
    { css: '"Mr De Haviland",cursive', g: 'Mr+De+Haviland' },
    { css: '"Mrs Saint Delafield",cursive', g: 'Mrs+Saint+Delafield' },
    { css: '"Nothing You Could Do",cursive', g: 'Nothing+You+Could+Do' },
    { css: '"Over the Rainbow",cursive', g: 'Over+the+Rainbow' },
    { css: '"Parisienne",cursive', g: 'Parisienne' },
    { css: '"Petit Formal Script",cursive', g: 'Petit+Formal+Script' },
    { css: '"Princess Sofia",cursive', g: 'Princess+Sofia' },
    { css: '"Qwigley",cursive', g: 'Qwigley' },
    { css: '"Redressed",cursive', g: 'Redressed' },
    { css: '"Rouge Script",cursive', g: 'Rouge+Script' },
    { css: '"Sacramento",cursive', g: 'Sacramento' },
    { css: '"Seaweed Script",cursive', g: 'Seaweed+Script' },
    { css: '"Sofia",cursive', g: 'Sofia' },
    { css: '"Square Peg",cursive', g: 'Square+Peg' },
    { css: '"Tangerine",cursive', g: 'Tangerine:wght@400;700' },
    { css: '"The Girl Next Door",cursive', g: 'The+Girl+Next+Door' },
    { css: '"Updock",cursive', g: 'Updock' },
    { css: '"Vibur",cursive', g: 'Vibur' },
    { css: '"Waiting for the Sunrise",cursive', g: 'Waiting+for+the+Sunrise' },
    { css: '"Yellowtail",cursive', g: 'Yellowtail' },
    { css: '"Yesteryear",cursive', g: 'Yesteryear' },
    { css: '"Zeyada",cursive', g: 'Zeyada' },
    { css: '"Allura",cursive', g: 'Allura' },
    { css: '"Alex Brush",cursive', g: 'Alex+Brush' },
    { css: '"Calligraffitti",cursive', g: 'Calligraffitti' },
    { css: '"Clicker Script",cursive', g: 'Clicker+Script' },
    { css: '"Engagement",cursive', g: 'Engagement' },
    { css: '"Italianno",cursive', g: 'Italianno' },
    { css: '"Norican",cursive', g: 'Norican' },
    { css: '"Pinyon Script",cursive', g: 'Pinyon+Script' },
    { css: '"Style Script",cursive', g: 'Style+Script' },
    { css: '"WindSong",cursive', g: 'WindSong' }
  ];

  // ---- フォント選択の「ゆらぎ」----
  // 円周率・アクセス時刻(ミリ秒)・画面・端末・時差・言語・乱数…“さまざまな条件”を混ぜて指標を作る。
  // 同じ瞬間は二度と来ない＝見る人ごと・瞬間ごとに違う一書体が現れる（バタフライエフェクト的な何か）。
  var PI = '31415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095505822317253594081284811174502841027019385211055596446229489549303819644288109756659334461284756482337867831652712019091456485669234603486104543266482133936072602491412737245870066';
  var now = new Date();
  var CAPITAL = 969696; // bombの資本金 ¥969,696 — 会社の素を“ゆらぎ”に織り込む
  var conds = [
    CAPITAL,
    Date.now(),
    Math.floor(((window.performance && performance.now) ? performance.now() : 0) * 1000),
    now.getMilliseconds(),
    now.getHours() * 3600 + now.getMinutes() * 60 + now.getSeconds(),
    (screen.width || 1) * (screen.height || 1),
    Math.round((window.devicePixelRatio || 1) * 1000),
    -now.getTimezoneOffset(),
    (navigator.language || '').length + (navigator.languages ? navigator.languages.length : 0),
    Math.floor(Math.random() * 2147483647)
  ];
  var list = (document.documentElement.lang === 'en') ? en : ja;
  var seed = 1;
  var piOff = (Date.now() + CAPITAL) % (PI.length - 9); // 時刻＋資本金で π の読み出し位置を決める
  for (var ci = 0; ci < conds.length; ci++) {
    var piChunk = parseInt(PI.substr((piOff + ci * 9) % (PI.length - 9), 9), 10) || 1;
    seed = (seed + ((conds[ci] % 1000003) + 1) * (piChunk % 9973 + 1)) % 2147483647;
  }
  seed = (seed ^ (seed >> 13) ^ (seed << 5)) >>> 0;
  var f = list[seed % list.length];
  var l = document.createElement('link');
  l.rel = 'stylesheet';
  l.href = 'https://fonts.googleapis.com/css2?family=' + f.g + '&display=swap';
  document.head.appendChild(l);
  document.documentElement.style.setProperty('--font', f.css);
})();
